name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container: golang:1.18

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: go test -race -cover ./...
