name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container: golang:1.18

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: go test -v -race -cover ./...

  integration-test:
    runs-on: ubuntu-latest
    container: golang:1.18

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install our binaries
        run:  go install ./cmd/...

      - name: Install (un)zip
        run:  apt update && apt-get install -y zip

      - name: Install dependencies
        run:  cd .. &&
              wget https://bitcoincore.org/bin/bitcoin-core-24.0.1/bitcoin-24.0.1-x86_64-linux-gnu.tar.gz &&
              tar xfz bitcoin-24.0.1-x86_64-linux-gnu.tar.gz && 
              mv bitcoin-24.0.1/bin/* /usr/local/bin/ &&
              wget https://github.com/lightningnetwork/lnd/releases/download/v0.15.5-beta/lnd-linux-amd64-v0.15.5-beta.tar.gz &&
              tar xfz lnd-linux-amd64-v0.15.5-beta.tar.gz &&
              mv lnd-linux-amd64-v0.15.5-beta/* /usr/local/bin/ &&
              wget https://releases.hashicorp.com/vault/1.12.2/vault_1.12.2_linux_amd64.zip &&
              unzip vault_1.12.2_linux_amd64.zip &&
              mv vault /usr/local/bin/

      - name: Run integration tests
        run:  go test -v -race -tags="itest" -cover .
